# Generated by Django 5.2.7 on 2025-11-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='expirationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
