# Generated by Django 5.2.7 on 2025-10-28 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='membershipName',
            field=models.IntegerField(choices=[(1, '1 Month'), (2, '3 Month'), (3, '6 Month'), (4, '10 Credits'), (5, '20 Credits')], default=1),
        ),
    ]
