# Generated by Django 5.2.7 on 2025-11-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0002_usermodel_expirationdate_usermodel_startdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='userId',
            new_name='id',
        ),
    ]
