# Generated by Django 5.2.7 on 2025-11-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0003_rename_userid_usermodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookedclass',
            old_name='user',
            new_name='userId',
        ),
    ]
