# Generated by Django 5.2.7 on 2025-11-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0004_rename_user_bookedclass_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookedClass',
            new_name='BookedClasses',
        ),
    ]
