# Generated by Django 5.2.7 on 2025-11-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0005_rename_bookedclass_bookedclasses'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='class_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_start_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_date',
            field=models.DateField(),
        ),
    ]
