# Generated by Django 5.2.7 on 2025-11-11 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0006_classes_class_end_time_classes_class_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedclasses',
            name='clasId',
        ),
        migrations.AddField(
            model_name='bookedclasses',
            name='classId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='userAPI.classes'),
        ),
        migrations.AlterField(
            model_name='bookedclasses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bookedclasses',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='booked_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
