# Generated by Django 5.2.7 on 2025-11-11 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0007_remove_bookedclasses_clasid_bookedclasses_classid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='class_end_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='class_start_time',
            new_name='start_time',
        ),
    ]
