# Generated by Django 5.2.7 on 2025-11-11 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0008_rename_class_end_time_classes_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='expirationDate',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='membershipName',
        ),
        migrations.CreateModel(
            name='MembershipsBought',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('membership', models.CharField(choices=[('Monthly', 'Monthly'), ('3 Months', '3 Months'), ('6 Months', '6 Months'), ('10 Credits', '10 Credits'), ('20 Credits', '20 Credits')], default=None, max_length=20)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('userId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='membership_bought', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
