# Generated by Django 5.2.7 on 2025-11-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0009_remove_usermodel_expirationdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
