# Generated by Django 5.2.7 on 2025-11-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0010_rename_startdate_usermodel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classes',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
