# Generated by Django 5.2.7 on 2025-11-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0011_classes_is_booked_classes_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='is_booked',
        ),
    ]
