# Generated by Django 5.2.7 on 2025-11-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0012_remove_classes_is_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipsbought',
            name='credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
