# Generated by Django 5.2.7 on 2025-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0012_remove_classes_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
