# Generated by Django 5.2.7 on 2025-11-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0013_membershipsbought_credits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipsbought',
            old_name='credits',
            new_name='credits_remaining',
        ),
    ]
