# Generated by Django 5.2.7 on 2025-11-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0013_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
