# Generated by Django 5.2.7 on 2025-11-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0014_rename_credits_membershipsbought_credits_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedclasses',
            name='credit',
            field=models.BooleanField(default=False),
        ),
    ]
