# Generated by Django 5.2.7 on 2025-11-14 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0015_rename_description_event_event_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
    ]
