# Generated by Django 5.2.7 on 2025-11-19 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0015_bookedclasses_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedclasses',
            name='credit',
        ),
        migrations.AddField(
            model_name='bookedclasses',
            name='membershipId',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='userAPI.membershipsbought'),
        ),
    ]
